name: Double Dot Labs
description: Developing for developers.
url: https://doubledotlabs.github.io
baseurl: "/"

collections:
    types:
        output: false
    projects:
        output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

include:
  - .scripts
