name: Double Dot Labs
description: "A community of open source developers and designers building things for the community."
icon: "/images/logo.png"
image: "/images/doubledot.png"

url: "https://doubledotlabs.github.io"
domainurl: "https://doubledotlabs.github.io"
baseurl: "/"

collections:
    blogs:
        output: true
        permalink: /blog/:year-:month-:day-:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

sass:
    sass_dir: ./css

plugins:
  - jekyll-sitemap
