name: Double Dot Labs
email: "mail@doubledot.dev"
description: "A group of developers and designers building things for the open source community."
icon: "/images/logo.png"
image: "/images/doubledot.png"

url: "https://doubledot.dev"
domainurl: "https://doubledot.dev"
baseurl: "/"
repository: doubledotlabs/DoubleDotLabs.github.io

collections:
    posts:
        output: true
        permalink: /blog/:year-:month-:day-:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

sass:
    sass_dir: ./css

plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
